FROM docker.io/library/fedora:43

# Install Rust
RUN dnf update -y && dnf install -y curl
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustc --version
RUN rustup component add rust-src --toolchain nightly

# Build vship
RUN dnf install -y clang ffms2-devel libavutil-free-devel git hipcc rocm
RUN mkdir /vship
WORKDIR /vship
RUN git clone https://codeberg.org/Line-fr/Vship.git ./
RUN make build BACKEND=HIP ARCH=ALL && make buildFFVSHIP && make install PREFIX=/usr

RUN mkdir /xav
WORKDIR /xav
COPY ./ /xav
RUN dnf install -y glibc-static libstdc++-static nasm rustup clang clang-libs llvm lld compiler-rt llvm-libunwind-static autoconf automake libtool cmake ninja-build pkgconf meson ffmpeg curl
RUN dnf install -y ffmpeg-free-devel gpac mkvtoolnix ffmpeg-free
RUN /xav/build.sh static_tq hdr
RUN cp /xav/target/release/xav /usr/bin/xav
